[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Brian van de Boogaard <brian.boogaard@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
